'''
Created on Feb 16, 2014

@author: noskillz
'''
REMITTANCE_STATUS_CREATED = 100
REMITTANCE_STATUS_FUNDS_PAID = 101

FUND_STATUS_UNTOUCHED = 200
FUND_STATUS_WAITING_FOR_PRICE = 201
FUND_STATUS_LBC_AD_SUBMITTED = 202
FUND_STATUS_FULFILLED = 203

LBC_AD_STATUS_CREATED = 300
LBC_AD_STATUS_POSTED = 301
LBC_AD_STATUS_VERIFYING = 302
LBC_AD_STATUS_ESCROW_RELEASED = 303

INCOMING_MONEY_STATUS_START = 400
INCOMING_MONEY_STATUS_PARTIAL = 401
INCOMING_MONEY_STATUS_PENDING_FULL = 402
INCOMING_MONEY_STATUS_RECEIVED = 403